version: '3.7'

services:
  sqs:
#    image: graze/sqs-local
    image: softwaremill/elasticmq-native:latest
    container_name: "fila_sqs"
    restart: unless-stopped
    volumes:
      - ./docker/sqs/elasticmq.conf:/opt/elasticmq.conf
    ports:
      - '9324:9324'
      - '9325:9325'

  sqs-request:
    image: node:16-alpine
    container_name: "processador_sqs"
    restart: unless-stopped
    depends_on:
      - sqs
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=fakeAccessKey
      - AWS_SECRET_ACCESS_KEY=fakeSecretKey
      - SQS_REGION=sa-east-1
      - QUEUE_NAME=exemplo_fila
      - QUEUE_URL=http://10.0.0.13:9324
      - MAX_IN_FLIGHT=1
      - BATCH_SIZE=1
      - POOL_INTERVAL_MS=200
      - DELAY_SECS=0
      - DEBUG_SQUISS=
      - "AWS_ENDPOINT=http://sqs:9324"
